Repository bow-swift/bow, pull requests merged in 2019-06, with the labels that each got.

#335 Result API docs and minor fixes
  Sources/Bow/Data/NonEmptyArray.swift
  Sources/Bow/Data/Result.swift
  contents/Documentation/Quick start.playground/Pages/Resources.xcplaygroundpage/Contents.swift
  contents/Documentation/Quick start.playground/contents.xcplayground
Labels: documentation, enhancement

#339 Docs versioning
  .gitignore
  .travis.yml
  docs/.gitignore
  docs/_includes/_footer.html
  docs/_includes/_header.html
  docs/_includes/_main.html
  docs/_includes/_nav.html
  docs/_includes/_sidebar-wrapper.html
  docs/_sass/components/_masthead.scss
  scripts/gen-docs.rb
Labels: documentation, website

#342 Lenses for Tuples
  Bow.xcodeproj/project.pbxproj
  Sources/BowOptics/Tuple/Tuple10.swift
  Sources/BowOptics/Tuple/Tuple2.swift
  Sources/BowOptics/Tuple/Tuple3.swift
  Sources/BowOptics/Tuple/Tuple4.swift
  Sources/BowOptics/Tuple/Tuple5.swift
  Sources/BowOptics/Tuple/Tuple6.swift
  Sources/BowOptics/Tuple/Tuple7.swift
  Sources/BowOptics/Tuple/Tuple8.swift
  Sources/BowOptics/Tuple/Tuple9.swift
Labels: enhancement

#345 Add error handling docs
  contents/Documentation/Documentation.xcodeproj/project.pbxproj
  contents/Documentation/Patterns.playground/Pages/Error handling.xcplaygroundpage/Contents.swift
  contents/Documentation/Patterns.playground/contents.xcplayground
  contents/Documentation/Podfile.lock
  docs/index.md
Labels: documentation

#348 Add missing functions
  Sources/Bow/Arrow/Kleisli.swift
  Sources/Bow/Data/Option.swift
  Sources/Bow/Data/Validated.swift
  Sources/Bow/Transformers/EitherT.swift
  Sources/Bow/Transformers/StateT.swift
  Sources/Bow/Typeclasses/ApplicativeError.swift
  Tests/BowTests/Data/ValidatedTest.swift
Labels: enhancement

#349 Add API docs for Reducible
  Sources/Bow/Typeclasses/Reducible.swift
Labels: documentation

#351 New encoding for type classes in Optics
  Bow.xcodeproj/project.pbxproj
  Sources/BowOptics/DSL/At+Optics.swift
  Sources/BowOptics/DSL/Each+Optics.swift
  Sources/BowOptics/DSL/Index+Optics.swift
  Sources/BowOptics/DSL/Kind+Optics.swift
  Sources/BowOptics/Fold.swift
  Sources/BowOptics/Getter.swift
  Sources/BowOptics/Instances/ArrayKOpticsInstances.swift
  Sources/BowOptics/Instances/EitherOpticsInstances.swift
  Sources/BowOptics/Instances/NonEmptyArrayOpticsInstances.swift
  Sources/BowOptics/Instances/OptionOpticsInstances.swift
  Sources/BowOptics/Instances/StringOpticsInstances.swift
  Sources/BowOptics/Instances/TryOpticsInstances.swift
  Sources/BowOptics/Iso.swift
  Sources/BowOptics/Lens.swift
  Sources/BowOptics/Optional.swift
  Sources/BowOptics/Prism.swift
  Sources/BowOptics/STD/ArrayK+Optics.swift
  Sources/BowOptics/STD/Either+Optics.swift
  Sources/BowOptics/STD/Id+Optics.swift
  Sources/BowOptics/STD/NonEmptyArray+Optics.swift
  Sources/BowOptics/STD/Option+Optics.swift
  Sources/BowOptics/STD/String+Optics.swift
  Sources/BowOptics/STD/Try+Optics.swift
  Sources/BowOptics/STD/Validated+Optics.swift
  Sources/BowOptics/Setter.swift
  Sources/BowOptics/Traversal.swift
  Sources/BowOptics/Typeclasses/At.swift
  Sources/BowOptics/Typeclasses/Each.swift
  Sources/BowOptics/Typeclasses/FilterIndex.swift
  Sources/BowOptics/Typeclasses/Index.swift
  Tests/BowOpticsTests/FoldTest.swift
  Tests/BowOpticsTests/GetterTest.swift
  Tests/BowOpticsTests/IsoTest.swift
  Tests/BowOpticsTests/Laws/IsoLaws.swift
  Tests/BowOpticsTests/Laws/LensLaws.swift
  Tests/BowOpticsTests/Laws/OptionalLaws.swift
  Tests/BowOpticsTests/Laws/PrismLaws.swift
  Tests/BowOpticsTests/Laws/SetterLaws.swift
  Tests/BowOpticsTests/Laws/TraversalLaws.swift
  Tests/BowOpticsTests/LensTest.swift
  Tests/BowOpticsTests/OptionalTest.swift
  Tests/BowOpticsTests/PrismTest.swift
  Tests/BowOpticsTests/SetterTest.swift
  Tests/BowOpticsTests/TestDomain.swift
  Tests/BowOpticsTests/TraversalTest.swift
Labels: enhancement

#357 Add API reference to optics type classes
  Sources/BowOptics/Typeclasses/At.swift
  Sources/BowOptics/Typeclasses/Cons.swift
  Sources/BowOptics/Typeclasses/Each.swift
  Sources/BowOptics/Typeclasses/FilterIndex.swift
  Sources/BowOptics/Typeclasses/Index.swift
  Sources/BowOptics/Typeclasses/Snoc.swift
Labels: documentation

#361 Add API reference for optics instances
  Sources/BowOptics/Instances/ArrayKOpticsInstances.swift
  Sources/BowOptics/Instances/ArrayOpticsInstances.swift
  Sources/BowOptics/Instances/ConstOpticsInstances.swift
  Sources/BowOptics/Instances/EitherKOpticsInstances.swift
  Sources/BowOptics/Instances/EitherOpticsInstances.swift
  Sources/BowOptics/Instances/IdOpticsInstances.swift
  Sources/BowOptics/Instances/IorOpticsInstances.swift
  Sources/BowOptics/Instances/NonEmptyArrayOpticsInstances.swift
  Sources/BowOptics/Instances/OptionOpticsInstances.swift
  Sources/BowOptics/Instances/StringOpticsInstances.swift
  Sources/BowOptics/Instances/TryOpticsInstances.swift
  Sources/BowOptics/Instances/ValidatedOpticsInstances.swift
Labels: documentation

#363 Add API reference for utility optics for core data types
  Sources/BowOptics/STD/ArrayK+Optics.swift
  Sources/BowOptics/STD/Either+Optics.swift
  Sources/BowOptics/STD/Id+Optics.swift
  Sources/BowOptics/STD/Ior+Optics.swift
  Sources/BowOptics/STD/NonEmptyArray+Optics.swift
  Sources/BowOptics/STD/Option+Optics.swift
  Sources/BowOptics/STD/Result+Optics.swift
  Sources/BowOptics/STD/String+Optics.swift
  Sources/BowOptics/STD/Try+Optics.swift
  Sources/BowOptics/STD/Validated+Optics.swift
Labels: documentation

#373 Add API reference for Iso
  Sources/BowOptics/Fold.swift
  Sources/BowOptics/Getter.swift
  Sources/BowOptics/Iso.swift
  Sources/BowOptics/Lens.swift
  Sources/BowOptics/Optional.swift
  Sources/BowOptics/Prism.swift
  Sources/BowOptics/Setter.swift
  Sources/BowOptics/Traversal.swift
  Tests/BowOpticsTests/FoldTest.swift
  Tests/BowOpticsTests/GetterTest.swift
  Tests/BowOpticsTests/IsoTest.swift
  Tests/BowOpticsTests/LensTest.swift
  Tests/BowOpticsTests/OptionalTest.swift
  Tests/BowOpticsTests/PrismTest.swift
  Tests/BowOpticsTests/SetterTest.swift
  Tests/BowOpticsTests/TestDomain.swift
  Tests/BowOpticsTests/TraversalTest.swift
Labels: documentation

#376 Add API reference for Lens
  Sources/BowOptics/Lens.swift
Labels: documentation

#378 Add API docs for Getter
  Sources/BowOptics/Getter.swift
Labels: documentation

#379 Add API docs for Setter and BoundSetter
  Sources/BowOptics/BoundSetter.swift
  Sources/BowOptics/Setter.swift
Labels: documentation
