Repository bow-swift/bow, pull requests merged in 2019-03, with the labels that each got.

#168 Add docs for FunctorFilter, MonadFilter and TraverseFilter
  Sources/Bow/Typeclasses/FunctorFilter.swift
  Sources/Bow/Typeclasses/MonadFilter.swift
  Sources/Bow/Typeclasses/TraverseFilter.swift
Labels: documentation

#151 API docs for Invariant, Functor, Applicative and Monad
  Sources/Bow/Typeclasses/Applicative.swift
  Sources/Bow/Typeclasses/Functor.swift
  Sources/Bow/Typeclasses/Invariant.swift
  Sources/Bow/Typeclasses/Monad.swift
  Sources/BowRecursionSchemes/Recursion.swift
Labels: documentation

#179 Add docs for MonadCombine, MonadReader, MonadState and MonadWriter
  Sources/Bow/Typeclasses/MonadCombine.swift
  Sources/Bow/Typeclasses/MonadReader.swift
  Sources/Bow/Typeclasses/MonadState.swift
  Sources/Bow/Typeclasses/MonadWriter.swift
Labels: documentation

#174 Add docs for FunctionK
  Sources/Bow/Arrow/FunctionK.swift
  Sources/Bow/Data/Coproduct.swift
  Sources/BowFree/Cofree.swift
  Sources/BowFree/Free.swift
  Tests/BowFreeTests/FreeTest.swift
Labels: documentation

#172 Add docs for Function1
  Sources/Bow/Arrow/Function1.swift
Labels: documentation

#170 Add docs for Function0
  Sources/Bow/Arrow/Function0.swift
Labels: documentation

#164 API docs for ApplicativeError and MonadError
  Sources/Bow/Typeclasses/ApplicativeError.swift
  Sources/Bow/Typeclasses/MonadError.swift
Labels: documentation

#155 API docs for SemigroupK, MonoidK and Alternative
  Sources/Bow/Typeclasses/Alternative.swift
  Sources/Bow/Typeclasses/MonoidK.swift
  Sources/Bow/Typeclasses/SemigroupK.swift
Labels: documentation

#161 API docs for Comonad and Bimonad
  Sources/Bow/Typeclasses/Bimonad.swift
  Sources/Bow/Typeclasses/Comonad.swift
Labels: documentation

#158 API docs for EquatableK and Comparable
  Sources/Bow/Typeclasses/Comparable.swift
  Sources/Bow/Typeclasses/EquatableK.swift
Labels: documentation

#184 Make token content expanded by default, improve hash links behaviour
  docs/extra/bow-jazzy-theme/assets/css/jazzy.css.scss
  docs/extra/bow-jazzy-theme/assets/js/jazzy.js
  docs/extra/bow-jazzy-theme/templates/doc.mustache
  docs/extra/bow-jazzy-theme/templates/task.mustache
Labels: documentation

#199 Searchbar improvements
  docs/extra/bow-jazzy-theme/assets/css/jazzy.css.scss
  docs/extra/bow-jazzy-theme/assets/js/jazzy.search.js
  docs/extra/bow-jazzy-theme/assets/js/lunr.min.js
  docs/extra/bow-jazzy-theme/assets/js/typeahead.jquery.js
Labels: documentation, enhancement

#185 Add postfix operator for downcasting
  Sources/Bow/Arrow/Cokleisli.swift
  Sources/Bow/Arrow/Function0.swift
  Sources/Bow/Arrow/Function1.swift
  Sources/Bow/Arrow/Kleisli.swift
  Sources/Bow/Data/ArrayK.swift
  Sources/Bow/Data/Const.swift
  Sources/Bow/Data/Coproduct.swift
  Sources/Bow/Data/Day.swift
  Sources/Bow/Data/DictionaryK.swift
  Sources/Bow/Data/Either.swift
  Sources/Bow/Data/Eval.swift
  Sources/Bow/Data/Id.swift
  Sources/Bow/Data/Ior.swift
  Sources/Bow/Data/Moore.swift
  Sources/Bow/Data/NonEmptyArray.swift
  Sources/Bow/Data/Option.swift
  Sources/Bow/Data/SetK.swift
  Sources/Bow/Data/State.swift
  Sources/Bow/Data/Store.swift
  Sources/Bow/Data/Sum.swift
  Sources/Bow/Data/Try.swift
  Sources/Bow/Data/Validated.swift
  Sources/Bow/Syntax/HigherKinds.swift
  Sources/Bow/Transformers/EitherT.swift
  Sources/Bow/Transformers/OptionT.swift
  Sources/Bow/Transformers/StateT.swift
  Sources/Bow/Transformers/WriterT.swift
  Sources/BowBrightFutures/FutureK.swift
  Sources/BowEffects/IO.swift
  Sources/BowFree/Cofree.swift
  Sources/BowFree/Coyoneda.swift
  Sources/BowFree/Free.swift
  Sources/BowFree/Yoneda.swift
  Sources/BowRecursionSchemes/Data/Fix.swift
  Sources/BowRecursionSchemes/Data/Mu.swift
  Sources/BowRecursionSchemes/Data/Nu.swift
  Sources/BowRx/MaybeK.swift
  Sources/BowRx/ObservableK.swift
  Sources/BowRx/SingleK.swift
  Tests/BowFreeTests/FreeTest.swift
Labels: enhancement

#187 Add API docs for Contravariant
  Sources/Bow/Typeclasses/Contravariant.swift
Labels: documentation

#192 Add API docs for Foldable and Traverse
  Sources/Bow/Typeclasses/Foldable.swift
  Sources/Bow/Typeclasses/Traverse.swift
Labels: documentation

#194 Add API docs for NonEmptyReducible
  Sources/Bow/Typeclasses/Foldable.swift
  Sources/Bow/Typeclasses/NonEmptyReducible.swift
Labels: documentation

#197 Add API docs for Const
  Sources/Bow/Data/Const.swift
  Sources/Bow/Data/Either.swift
  Sources/Bow/Data/Id.swift
  Sources/Bow/Data/Option.swift
Labels: documentation

#198 Add API docs for SetK
  Sources/Bow/Data/SetK.swift
Labels: documentation

#200 Add API docs for Validated
  Sources/Bow/Data/Validated.swift
Labels: documentation

#203 Add API docs for Kleisli
  Sources/Bow/Arrow/Kleisli.swift
  Sources/Bow/Data/Reader.swift
Labels: documentation

#204 Add API docs for Coproduct
  Sources/Bow/Data/Coproduct.swift
Labels: documentation

#205 Add API docs for Try
  Sources/Bow/Data/Try.swift
Labels: documentation

#210 Add API docs for EitherT
  Sources/Bow/Transformers/EitherT.swift
Labels: documentation

#211 Add API docs for OptionT
  Sources/Bow/Transformers/OptionT.swift
Labels: documentation

#212 Add API docs for StateT and State
  Sources/Bow/Data/State.swift
  Sources/Bow/Transformers/StateT.swift
Labels: documentation

#213 Add API docs for WriterT
  Sources/Bow/Transformers/WriterT.swift
Labels: documentation

#214 Add API docs for ArrayK
  Sources/Bow/Data/ArrayK.swift
Labels: documentation

#215 Add API docs for DictionaryK
  Sources/Bow/Data/DictionaryK.swift
Labels: documentation

#216 Add API docs for NonEmptyArray
  Sources/Bow/Data/NonEmptyArray.swift
Labels: documentation

#217 Add API docs for Ior
  Sources/Bow/Data/Ior.swift
Labels: documentation

#220 Add API docs for Cokleisli and Coreader
  Sources/Bow/Arrow/Cokleisli.swift
  Sources/Bow/Data/Coreader.swift
Labels: documentation
