Repository bow-swift/bow, pull requests merged in 2019-07, with the labels that each got.

#384 Versions deployment creator and web selector
  .travis.yml
  docs/_data/commons.yml
  docs/_data/doc-versions.yml
  docs/_data/menu.yml
  docs/_includes/_doc-versions.html
  docs/_includes/_head-docs.html
  docs/_includes/_head.html
  docs/_includes/_header.html
  docs/_includes/_home-doc-versions.html
  docs/_includes/_nav.html
  docs/_includes/_navigation-api-versions.html
  docs/_includes/_navigation-doc-versions.html
  docs/_includes/_sidebar-doc-versions.html
  docs/_sass/components/_buttons.scss
  docs/_sass/components/_doc-versions.scss
  docs/_sass/components/_masthead.scss
  docs/_sass/components/_navigation.scss
  docs/_sass/components/_sidebar-nav.scss
  docs/_sass/components/_wrapper.scss
  docs/css/docs.scss
  docs/css/styles.scss
  docs/js/doc-versions.js
  docs/js/docVersions.js
  scripts/gen-docs.rb
Labels: documentation, website

#334 Docs Bow version selector
  .travis.yml
  docs/_includes/_head-docs.html
  docs/_includes/_head.html
  docs/_includes/_nav.html
  docs/_includes/_navigation-api-versions.html
  docs/_includes/_navigation-doc-versions.html
  docs/_includes/_sidebar-doc-versions.html
  docs/_includes/_sidebar-wrapper.html
  docs/_sass/components/_buttons.scss
  docs/_sass/components/_doc-versions.scss
  docs/_sass/components/_masthead.scss
  docs/_sass/components/_navigation.scss
  docs/_sass/components/_sidebar-nav.scss
  docs/_sass/components/_wrapper.scss
  docs/css/docs.scss
  docs/css/styles.scss
  docs/js/doc-versions.js
  scripts/gen-docs.rb
Labels: website

#385 Add a leading slash to have URLs as absolute
  docs/_includes/_navigation-api-versions.html
  docs/_includes/_navigation-doc-versions.html
  docs/_includes/_sidebar-doc-versions.html
Labels: website

#388 Add API reference for Coproducts
  Sources/BowGeneric/Coproduct10.swift
  Sources/BowGeneric/Coproduct2.swift
  Sources/BowGeneric/Coproduct3.swift
  Sources/BowGeneric/Coproduct4.swift
  Sources/BowGeneric/Coproduct5.swift
  Sources/BowGeneric/Coproduct6.swift
  Sources/BowGeneric/Coproduct7.swift
  Sources/BowGeneric/Coproduct8.swift
  Sources/BowGeneric/Coproduct9.swift
Labels: documentation

#380 Add API reference for Optional
  Sources/BowOptics/Optional.swift
Labels: documentation

#383 Add API reference for Traversal
  Sources/BowOptics/Traversal.swift
Labels: documentation

#382 Add API reference for Fold
  Sources/BowOptics/Fold.swift
Labels: documentation

#381 Add API reference for Prism
  Sources/BowOptics/Prism.swift
Labels: documentation

#386 Documentation for Optics
  contents/Documentation/Documentation.xcworkspace/contents.xcworkspacedata
  contents/Documentation/Optics.playground/Pages/Automatic derivation.xcplaygroundpage/Contents.swift
  contents/Documentation/Optics.playground/Pages/Composition.xcplaygroundpage/Contents.swift
  contents/Documentation/Optics.playground/Pages/Overview.xcplaygroundpage/Contents.swift
  contents/Documentation/Optics.playground/Pages/Writing your own optics.xcplaygroundpage/Contents.swift
  contents/Documentation/Optics.playground/contents.xcplayground
  contents/Documentation/Optics.playground/playground.xcworkspace/contents.xcworkspacedata
Labels: documentation

#394 Refactor Eval
  Bow.xcodeproj/project.pbxproj
  Sources/Bow/Data/ArrayK.swift
  Sources/Bow/Data/Eval.swift
  Sources/Bow/Typeclasses/Foldable.swift
  Sources/BowFree/Cofree.swift
  Sources/BowRecursionSchemes/Recursion.swift
  Sources/BowRx/MaybeK.swift
  Sources/BowRx/ObservableK.swift
  Tests/BowGenerators/Data/Eval+Gen.swift
  Tests/BowTests/Data/EvalTest.swift
Labels: enhancement

#395 Utilities for monad comprehensions
  Bow.xcodeproj/project.pbxproj
  Sources/Bow/Typeclasses/MonadComprehensions/BindingExpression.swift
  Sources/Bow/Typeclasses/MonadComprehensions/BindingOperator.swift
  Sources/Bow/Typeclasses/MonadComprehensions/BoundVar.swift
  Sources/Bow/Typeclasses/MonadComprehensions/MonadComprenhensions.swift
  Sources/Bow/Typeclasses/MonadComprehensions/ReaderBindingExpression.swift
  Sources/Bow/Typeclasses/MonadComprehensions/StateBindingExpression.swift
  Sources/Bow/Typeclasses/MonadComprehensions/WriterBindingExpression.swift
  Tests/BowLaws/BindingOperatorOverload.swift
  Tests/BowLaws/MonadLaws.swift
  Tests/BowLaws/MonadStateLaws.swift
  Tests/BowLaws/MonadWriterLaws.swift
  Tests/BowTests/Arrow/KleisliTest.swift
Labels: enhancement
